### ISSUE TITLE
SD card sample update needed

### ISSUE THREAD

**Issue by patridge** [WildernessLabs/Meadow.Core.Samples#51]
http://developer.wildernesslabs.co/Meadow/Meadow.OS/Core-Compute_SD_Card/

Not sure on the code itself yet, but the meadow.config.yaml is missing the required device setting ([docs](http://developer.wildernesslabs.co/Meadow/Meadow.OS/Core-Compute_SD_Card/) ).

```yaml
Device:
    # Enable if your Meadow build is using SD card hardware.
    SdStorageSupported: true
```
